INSERT INTO tarot_card (name, meaning) VALUES
                                           ('The Fool', 'New beginnings, optimism, trust in life.'),
                                           ('The Magician', 'Action, the power to manifest.'),
                                           ('The High Priestess', 'Inaction, going within, the subconscious.'),
                                           ('The Empress', 'Abundance, nurturing, fertility, life in bloom!'),
                                           ('The Emperor', 'Structure, stability, rules and power.'),
                                           ('The Hierophant', 'Institutions, tradition, society and its rules.'),
                                           ('The Lovers', 'Sexuality, passion, choice, uniting.'),
                                           ('The Chariot', 'Movement, progress, integration.'),
                                           ('Strength', 'Courage, subtle power, integration of animal self.'),
                                           ('The Hermit', 'Meditation, solitude, consciousness.'),
                                           ('Wheel of Fortune', 'Cycles, change, ups and downs.'),
                                           ('Justice', 'Fairness, equality, balance.'),
                                           ('The Hanged Man', 'Surrender, new perspective, enlightenment.'),
                                           ('Death', 'The end of something, change, the impermeability of all things.'),
                                           ('Temperance', 'Balance, moderation, being sensible.'),
                                           ('The Devil', 'Destructive patterns, addiction, giving away your power.'),
                                           ('The Tower', 'Collapse of stable structures, release, sudden insight.'),
                                           ('The Star', 'Hope, calm, a good omen!'),
                                           ('The Moon', 'Mystery, the subconscious, dreams.'),
                                           ('The Sun', 'Success, happiness, all will be well.'),
                                           ('Judgement', 'Rebirth, a new phase, inner calling.'),
                                           ('The World', 'Completion, wholeness, attainment, celebration of life.');

INSERT INTO tarot_card (name, meaning) VALUES
                                           ('Ace of Wands', 'New beginnings, creative spark, fertile ideas.'),
                                           ('Two of Wands', 'Planning, making decisions, leaving home.'),
                                           ('Three of Wands', 'Looking ahead, expansion, rapid growth.'),
                                           ('Four of Wands', 'Community, home, celebration.'),
                                           ('Five of Wands', 'Competition, conflict, rivalry.'),
                                           ('Six of Wands', 'Victory, success, public reward.'),
                                           ('Seven of Wands', 'Perseverance, defensive, maintaining control.'),
                                           ('Eight of Wands', 'Rapid action, movement, quick decisions.'),
                                           ('Nine of Wands', 'Resilience, grit, last stand.'),
                                           ('Ten of Wands', 'Burden, responsibility, hard work.'),
                                           ('Page of Wands', 'Exploration, excitement, freedom.'),
                                           ('Knight of Wands', 'Action, adventure, fearlessness.'),
                                           ('Queen of Wands', 'Courage, determination, joy.'),
                                           ('King of Wands', 'Big picture, leader, overcoming challenges.');

INSERT INTO tarot_card (name, meaning) VALUES
                                           ('Ace of Cups', 'Love, new relationships, compassion.'),
                                           ('Two of Cups', 'Unity, partnership, connection.'),
                                           ('Three of Cups', 'Friendship, community, happiness.'),
                                           ('Four of Cups', 'Apathy, contemplation, disconnectedness.'),
                                           ('Five of Cups', 'Loss, grief, self-pity.'),
                                           ('Six of Cups', 'Nostalgia, memories, childhood.'),
                                           ('Seven of Cups', 'Choices, fantasy, illusion.'),
                                           ('Eight of Cups', 'Walking away, disillusionment, leaving behind.'),
                                           ('Nine of Cups', 'Satisfaction, emotional stability, luxury.'),
                                           ('Ten of Cups', 'Inner happiness, fulfillment, dreams coming true.'),
                                           ('Page of Cups', 'Creative opportunities, curiosity, possibility.'),
                                           ('Knight of Cups', 'Romance, charm, imagination.'),
                                           ('Queen of Cups', 'Compassion, calm, comfort.'),
                                           ('King of Cups', 'Emotional balance, generosity, diplomacy.');

INSERT INTO tarot_card (name, meaning) VALUES
                                           ('Ace of Swords', 'Breakthrough, clarity, sharp mind.'),
                                           ('Two of Swords', 'Difficult choices, indecision, stalemate.'),
                                           ('Three of Swords', 'Heartbreak, suffering, grief.'),
                                           ('Four of Swords', 'Rest, restoration, contemplation.'),
                                           ('Five of Swords', 'Unbridled ambition, win at all costs, sneakiness.'),
                                           ('Six of Swords', 'Transition, leaving behind, moving on.'),
                                           ('Seven of Swords', 'Deception, trickery, tactics and strategy.'),
                                           ('Eight of Swords', 'Imprisonment, entrapment, self-victimization.'),
                                           ('Nine of Swords', 'Anxiety, hopelessness, nightmares.'),
                                           ('Ten of Swords', 'Failure, collapse, defeat.'),
                                           ('Page of Swords', 'Curiosity, restlessness, mental energy.'),
                                           ('Knight of Swords', 'Action, speed, ambition.'),
                                           ('Queen of Swords', 'Complexity, perceptiveness, clear mindedness.'),
                                           ('King of Swords', 'Head over heart, discipline, truth.');

INSERT INTO tarot_card (name, meaning) VALUES
                                           ('Ace of Pentacles', 'Opportunity, prosperity, new venture.'),
                                           ('Two of Pentacles', 'Balancing decisions, priorities, adapting to change.'),
                                           ('Three of Pentacles', 'Teamwork, collaboration, building.'),
                                           ('Four of Pentacles', 'Conservation, security, frugality.'),
                                           ('Five of Pentacles', 'Need, poverty, insecurity.'),
                                           ('Six of Pentacles', 'Charity, generosity, sharing.'),
                                           ('Seven of Pentacles', 'Hard work, perseverance, diligence.'),
                                           ('Eight of Pentacles', 'Apprenticeship, passion, high standards.'),
                                           ('Nine of Pentacles', 'Fruits of labor, rewards, luxury.'),
                                           ('Ten of Pentacles', 'Legacy, culmination, inheritance.'),
                                           ('Page of Pentacles', 'Ambition, desire, diligence.'),
                                           ('Knight of Pentacles', 'Efficiency, hard work, responsibility.'),
                                           ('Queen of Pentacles', 'Practicality, creature comforts, financial security.'),
                                           ('King of Pentacles', 'Abundance, prosperity, security.');